modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://salt-and-fries.github.io/Salt-s-Inventory-Update/"
issueTrackerURL = "https://github.com/Salt-and-Fries/Salt-s-Inventory-Update/issues"
logoFile = "assets/salts_inventory_update/icon.png"
authors = "Salt"
description = "${description}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
